import type { SubscriptionPeriod, PricingPlan } from "@/types";

export const pricingPlans: Record<SubscriptionPeriod, PricingPlan[]> = {
  monthly: [
    {
      name: "Starter",
      plan: "starter",
      price: 29,
      period: "monthly",
      features: [
        "Basic Auto Trading",
        "Manual Trading",
        "Real-time Market Data",
        "Portfolio Tracking",
        "Email Support",
      ],
    },
    {
      name: "Professional",
      plan: "professional",
      price: 79,
      period: "monthly",
      featured: true,
      features: [
        "Advanced Auto Trading",
        "Multiple Strategies",
        "Manual Trading",
        "Real-time Market Data",
        "AI Predictions (7-day)",
        "Portfolio Analytics",
        "Priority Support",
        "API Access",
      ],
    },
    {
      name: "Enterprise",
      plan: "enterprise",
      price: 199,
      period: "monthly",
      features: [
        "Unlimited Auto Trading",
        "Custom Strategies",
        "All Manual Trading Features",
        "Full Market Data Access",
        "AI Predictions (30-day)",
        "Advanced Analytics",
        "Dedicated Support",
        "Full API Access",
        "White-label Options",
      ],
    },
  ],
  quarterly: [
    {
      name: "Starter",
      plan: "starter",
      price: 75,
      period: "quarterly",
      savings: "Save 14%",
      features: [
        "Basic Auto Trading",
        "Manual Trading",
        "Real-time Market Data",
        "Portfolio Tracking",
        "Email Support",
      ],
    },
    {
      name: "Professional",
      plan: "professional",
      price: 200,
      period: "quarterly",
      featured: true,
      savings: "Save 16%",
      features: [
        "Advanced Auto Trading",
        "Multiple Strategies",
        "Manual Trading",
        "Real-time Market Data",
        "AI Predictions (7-day)",
        "Portfolio Analytics",
        "Priority Support",
        "API Access",
      ],
    },
    {
      name: "Enterprise",
      plan: "enterprise",
      price: 500,
      period: "quarterly",
      savings: "Save 16%",
      features: [
        "Unlimited Auto Trading",
        "Custom Strategies",
        "All Manual Trading Features",
        "Full Market Data Access",
        "AI Predictions (30-day)",
        "Advanced Analytics",
        "Dedicated Support",
        "Full API Access",
        "White-label Options",
      ],
    },
  ],
  yearly: [
    {
      name: "Starter",
      plan: "starter",
      price: 250,
      period: "yearly",
      savings: "Save 28%",
      features: [
        "Basic Auto Trading",
        "Manual Trading",
        "Real-time Market Data",
        "Portfolio Tracking",
        "Email Support",
      ],
    },
    {
      name: "Professional",
      plan: "professional",
      price: 650,
      period: "yearly",
      featured: true,
      savings: "Save 31%",
      features: [
        "Advanced Auto Trading",
        "Multiple Strategies",
        "Manual Trading",
        "Real-time Market Data",
        "AI Predictions (7-day)",
        "Portfolio Analytics",
        "Priority Support",
        "API Access",
      ],
    },
    {
      name: "Enterprise",
      plan: "enterprise",
      price: 1600,
      period: "yearly",
      savings: "Save 33%",
      features: [
        "Unlimited Auto Trading",
        "Custom Strategies",
        "All Manual Trading Features",
        "Full Market Data Access",
        "AI Predictions (30-day)",
        "Advanced Analytics",
        "Dedicated Support",
        "Full API Access",
        "White-label Options",
      ],
    },
  ],
};
